### ISSUE TITLE
It would be nice if there was a clickable button that scrolled to the first patet-page

### ISSUE THREAD

**Issue by drakejacob** [cthit/nollk.it#18]
Currently there's only text instructing the user that they can scroll

**Comment by daancs** [comment]
Yes, I looked into this the other day and gave up after trying since it doesnt look like react-page-scroller has a built-in function for it. However, I see in inspect element that a certain div-element changes their translate3d to -100% everytime you scroll downwards and adds +100% anytime you scroll upwards. We could maybe try to manipulate that?

**Comment by daancs** [comment]
I might have figured it out, brb for pr
